### ISSUE TITLE
TODO list to improve documentation

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/reproschema#478]
## high level issues

For example, pages that should be merged or sections that should be extracted to become a page....

- [ ] extract [Tips and tricks](https://www.repronim.org/reproschema/53_tips_to_make_your_life_easier/) into its own page, maybe move some of it into the FAQ
- [ ] ~~actually add definitions to the glossary~~ (not needed anymore)
- [x] add sections to the FAQ
- [x] replace "what-did-we-add" sections of the tutorial with highlighting: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlighting-specific-lines -  done in #487
- [x] create jsonld files that hold the content that is displayed in the doc to make it possible to validate their content -  done in #487

## low level issues

- fixed in #482

For example formatting, file names and structure...

- [x] `about_this_doc` should become a CONTRIBUTING.md
- [x] remove numbers prefix in filenames
- [x] ensure that all code blocks have syntax highlighting
- [x] ensure proper formatting of markdown
      for example to avoid things like at the bottom of [this page](https://www.repronim.org/reproschema/43_create_new_assess/)

**Comment by yibeichan** [comment]
We should probably work on `README.md` files for all reproschema-related repos and make sure they can link to each other.

**Comment by Remi-Gau** [comment]
I am going to close this issue because most items are done AFAICT.

For the remaining points we can just open new issues.
